---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    #- name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      #- pause:
      #  seconds: 60
    - name: "Echo env var"
      ansible.builtin.debug:
        msg:
        - "Connection: {{ TYPEORM_CONNECTION }}"

    - name: "install python for Ansible."
      become: true
      raw: apt update && apt install -y python3

    - name: "install nodejs Ansible."
      become: true
      raw: apt install -y nodejs npm
  
    - name: "install pm2 for Ansible."
      become: true
      raw: npm install pm2 -g

    - name: "Setup environment variables"
      raw: |
        set ENVIRONMENT="production"
        set TYPEORM_CONNECTION="{{ TYPEORM_CONNECTION }}"
        set TYPEORM_ENTITIES="{{ TYPEORM_ENTITIES }}"
        set TYPEORM_HOST="{{ TYPEORM_HOST }}"
        set TYPEORM_PORT="{{ TYPEORM_PORT }}"
        set TYPEORM_USERNAME="{{ TYPEORM_USERNAME }}"
        set TYPEORM_PASSWORD="{{ TYPEORM_PASSWORD }}"
        set TYPEORM_DATABASE="{{ TYPEORM_DATABASE }}"
 
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/zutils/circleci-demo-javascript-express.git'
        dest: ~/circleci-demo-javascript-express

    - name: "Run Backend"
      raw: cd ~/circleci-demo-javascript-express/backend; pm2 start app.js

  roles:
    # Your code here
    - configure-server