---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT: "production"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"

  pre_tasks:
    #- name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      #- pause:
      #  seconds: 60
    - name: "Echo env var"
      ansible.builtin.debug:
        msg:
        - "Connection: {{ TYPEORM_CONNECTION }}"

    - name: "install python for Ansible."
      become: true
      raw: apt update && apt install -y python3

    - name: "install nodejs Ansible."
      become: true
      raw: apt install -y nodejs npm
  
    - name: "install pm2 for Ansible."
      become: true
      raw: npm install pm2 -g
  
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/zutils/cdond-c3-projectstarter.git'
        dest: ~/cdond-c3-projectstarter

    - name: "Run Backend"
      raw: cd ~/cdond-c3-projectstarter/backend; pm2 start "npm start"

  roles:
    # Your code here
    - configure-server